// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Infrastructure.Data;

#nullable disable

namespace StudentManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age").HasColumnType("int");
                    b.Property<string>("Course").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<DateTime>("CreatedDate").HasDefaultValueSql("GETUTCDATE()").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");

                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Students");

                    b.HasData(
                        new { Id = 1, Age = 24, Course = "Computer Science", CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Email = "akash@example.com", Name = "Akash Sharma" },
                        new { Id = 2, Age = 22, Course = "Data Science", CreatedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc), Email = "priya@example.com", Name = "Priya Patel" },
                        new { Id = 3, Age = 23, Course = "Machine Learning", CreatedDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc), Email = "rahul@example.com", Name = "Rahul Gupta" });
                });
#pragma warning restore 612, 618
        }
    }
}
